name: Build & deploy on tag

env:
  APP: tor

  # Capture groups within $TAG_FMT:
  #   \1 => TAG       vX.Y.Z[.P]+build<N>
  #   \2 => VERSION   vX.Y.Z[.P]
  #   \3 => ignore    (captures dot, and last number-group in version)
  #   \4 => BUILD     N
  TAG_FMT: '^refs/tags/((v[0-9]+(\.[0-9]+){2,3})\+build([0-9]+))$'


on:
  push:
    tags: [ '*' ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-24.04
          - arch: arm32v7
            platform: linux/arm/v7
            runner: ubuntu-24.04-arm
          - arch: arm64v8
            platform: linux/arm64/v8
            runner: ubuntu-24.04-arm

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: matrix.arch == 'arm32v7'
        uses: docker/setup-qemu-action@v4
        with:
          platforms: arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Setup environment
        run: |
          if ! echo "$GITHUB_REF" | grep -qE "$TAG_FMT"; then
            echo "ERR: TAG must be in format: vX.Y.Z[.P]+build<N>"
            exit 1
          fi

          VERSION="$(echo "$GITHUB_REF" | sed -E "s|$TAG_FMT|\2|")"

          {
            echo "TAG=$(echo "$GITHUB_REF" | sed -E "s|$TAG_FMT|\1|")"
            echo "VERSION=$VERSION"
            echo "TOR_VERSION=${VERSION#v}"
            echo "BUILD=$(echo "$GITHUB_REF" | sed -E "s|$TAG_FMT|\4|")"
          } >> "$GITHUB_ENV"

      - name: Print ENV VARs set above
        run: |
          printf "    APP: %s\n"  "$APP"
          printf "   ARCH: %s\n"  "${{ matrix.arch }}"
          printf "PLATFORM: %s\n" "${{ matrix.platform }}"
          printf "    TAG: %s\n"  "$TAG"
          printf "VERSION: %s\n"  "$VERSION"
          printf "TORVER: %s\n"   "$TOR_VERSION"
          printf "  BUILD: %s\n"  "$BUILD"

      - name: Build ${{ env.APP }}
        run: >
          docker buildx build --load --no-cache --provenance=false .
          --platform  "${{ matrix.platform }}"
          --build-arg "ARCH=${{ matrix.arch }}"
          --build-arg "VERSION=$TOR_VERSION"
          --label     "arch=${{ matrix.arch }}"
          --label     "commit=${{ github.sha }}"
          --label     "git-tag=$TAG"
          --label     "guilty=${{ github.actor }}"
          --label     "repo-url=${{ github.repositoryUrl }}"
          --tag       "$APP"

      - name: Show built image details
        run: docker images "$APP"

      - name: Save built image into a .tgz file
        run: |
          mkdir -p images/

          docker tag  "$APP"  "$APP:${{ matrix.arch }}"
          docker save "$APP:${{ matrix.arch }}" | gzip > "images/docker-$APP-$TAG-${{ matrix.arch }}.tgz"

      - name: Print sha256sum of built image
        run: sha256sum images/*
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-${{ matrix.arch }}
          path: images/

  deploy:
    name: Publish docker images

    runs-on: ubuntu-24.04
    needs: build

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - name: Setup environment
        run: |
          {
            echo "SLUG=$(echo "${GITHUB_REPOSITORY,,}" | sed 's/docker-//')"
            echo "VERSION=$(echo "$GITHUB_REF" | sed -E "s|$TAG_FMT|\2|")"
            echo "BUILD=$(echo "$GITHUB_REF" | sed -E "s|$TAG_FMT|\4|")"
          } >> "$GITHUB_ENV"

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: docker-images-*
          merge-multiple: true
          path: docker-images

      - name: Print sha256sum of downloaded images
        run: sha256sum docker-images/*

      - name: Load images locally
        run: find docker-images -type f -name '*.tgz' -exec docker load -i "{}" \;

      # No short tags.
      - name: Version-tag all images
        run: |
          for arch in $(docker images "$APP" --format "{{.Tag}}"); do
            docker tag  "$APP:$arch"  "$SLUG:$VERSION-$arch"
          done

      - name: List all tagged images
        run: docker images "$SLUG"

      - name: Login to Docker Hub
        env:
          DOCKER_USER: lnliz
        run: |
          echo "Logging in as ${DOCKER_USER}…"
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u="$DOCKER_USER" --password-stdin

      - name: Push all images
        run: docker images "$SLUG" --format "{{.Repository}}:{{.Tag}}" | xargs -I %  docker push %

      - name: Create manifest
        run: >
          docker -D manifest create  "$SLUG:$VERSION" \
            "$SLUG:$VERSION-amd64" \
            "$SLUG:$VERSION-arm32v7" \
            "$SLUG:$VERSION-arm64v8"

      - name: Annotate images for manifest
        run: |
          docker manifest annotate "$SLUG:$VERSION" "$SLUG:$VERSION-arm32v7" --os linux --arch arm   --variant v7
          docker manifest annotate "$SLUG:$VERSION" "$SLUG:$VERSION-arm64v8" --os linux --arch arm64 --variant v8

      - name: Print manifest details
        run: docker manifest inspect "$SLUG:$VERSION" | jq '.'

      - name: Push manifest
        run: docker manifest push "$SLUG:$VERSION"

      - name: Create & print SHA256SUMS file
        run: |
          (cd docker-images;  sha256sum *) >> ./SHA256SUMS
          cat ./SHA256SUMS
